# Generated by Django 5.1.2 on 2024-11-06 12:15

import members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_teammember_created_at_teammember_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[members.models.validate_phone_number]),
        ),
    ]
